---

- fail: msg="This role is for RedHat-like systems only"
  when: ansible_os_family != "RedHat"

- name: Install remi repo
  yum: 
   name: "{{ remi_repo_url }}"
   state: present
  when: state == 'present'

- name: Import remi GPG key.
  rpm_key:
    key: "{{ remi_repo_gpg_key_url }}"
    state: present
  when: state == 'present'

- name: Remove remi repo
  yum:
   name: remi*
   state: absent
  when: state == 'absent'

- name: Remove remi GPG key.
  rpm_key:
    key: "{{ remi_repo_gpg_key_url }}"
    state: absent 
  when: state == 'absent'
